FROM python:3.12

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/scr/app

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt
    
COPY . .
